# Generated by Django 5.2.17 on 2026-10-02 02:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nama')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nama')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='deskripsi')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='harga (Rp)')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='stok')),
                ('condition', models.CharField(choices=[('new', 'Baru'), ('like_new', 'Seperti Baru'), ('good', 'Kondisi Baik'), ('fair', 'Layak Pakai')], default='good', max_length=20, verbose_name='kondisi')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='merek')),
                ('weight_grams', models.PositiveIntegerField(default=500, help_text='Dipakai untuk perhitungan ongkir (RajaOngkir).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='berat (gram)')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='URL thumbnail')),
                ('is_active', models.BooleanField(default=True, help_text='Nonaktifkan untuk menyembunyikan listing dari katalog.', verbose_name='dipublikasikan')),
                ('source', models.CharField(choices=[('manual', 'Listing pengguna'), ('dummyjson', 'Seed DummyJSON')], default='manual', max_length=20, verbose_name='sumber data')),
                ('external_id', models.PositiveIntegerField(blank=True, help_text='ID produk pada sumber eksternal (mis. DummyJSON).', null=True, verbose_name='ID eksternal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='kategori')),
                ('seller', models.ForeignKey(blank=True, help_text='Kosong untuk data awal hasil seed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='penjual')),
            ],
            options={
                'verbose_name': 'produk',
                'verbose_name_plural': 'produk',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL gambar')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='teks alternatif')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='urutan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'gambar produk',
                'verbose_name_plural': 'gambar produk',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='product_pro_is_acti_411801_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source', 'external_id'), name='unique_product_external_id_per_source'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 1)), name='product_price_gte_1'),
        ),
    ]
