# Generated by Django 5.2.17 on 2026-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_unique_review_per_user_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
